name: Java CI with Maven - Rest Assured

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Verify Maven installation
      run: mvn -v

    - name: Install dependencies and run tests
      run: mvn clean test
