name: Java CI with Maven - Rest Assured

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ main ]

jobs:
  Run-Rest-Assured-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

<<<<<<< HEAD
      - name: Build and Run REST Assured Tests with Maven
        run: mvn test
=======
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
>>>>>>> 88e6449ffccb9b87794cb2cd2c31cd8c323ba61d

      - name: Archive REST-Assured results
        uses: actions/upload-artifact@v3
        with:
          name: REST-Assured-results
          path: target/surefire-reports
      - name: Upload REST-Assured results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: REST-Assured-results
          path: target/surefire-reports